export const LOGIN = 'action/LOGIN'
export const LOGIN_SUCCESS = 'action/LOGIN_SUCCESS'
export const LOGIN_FAIL = 'action/LOGIN_FAIL'
export const SIGNUP = 'action/SIGNUP'
export const SIGNUP_SUCCESS = 'action/SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'action/SIGNUP_FAIL'
export const LOGOUT = 'action/LOGOUT'

export const CREATE_NOTIFICATION = 'action/CREATE_NOTIFICATION'
export const DELETE_NOTIFICATION = 'action/DELETE_NOTIFICATION'
